import type { BidNotice, Topic } from "./types";

export const starterTopic: Topic = {
  id: "topic-transport",
  name: "대중교통 체계 개편",
  description: "시민 이동 편의와 운영 효율을 높이는 대중교통 노선·환승·요금·정보서비스 체계 개편 사업",
  capabilities: "교통 데이터 분석, 노선 개편 컨설팅, MaaS, 통합 정보 플랫폼, 시민 수요조사",
  includeKeywords: ["대중교통", "노선", "환승", "버스", "교통카드", "MaaS", "교통정보", "운영체계"],
  excludeKeywords: ["청소", "급식", "조경"],
  businessTypes: ["용역"],
  regions: ["전국"],
  minBudget: 50_000_000,
  maxBudget: 3_000_000_000,
  minimumDays: 3,
  threshold: 70,
};

const closesAt = (offset: number, hour = 10) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

const publishedAt = (offset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  date.setHours(14, 0, 0, 0);
  return date.toISOString();
};

export const mockNotices: BidNotice[] = [
  {
    id: "R26BK00125001-000",
    bidNumber: "R26BK00125001",
    order: "000",
    title: "2027년 대중교통 노선체계 개편 및 통합환승 운영방안 수립 용역",
    businessType: "용역",
    status: "신규",
    agency: "서울특별시",
    demandAgency: "서울특별시 교통실",
    region: "서울특별시",
    publishedAt: publishedAt(-1),
    closesAt: closesAt(8),
    budget: 1_240_000_000,
    budgetLabel: "추정가격 12억 4,000만원",
    contractMethod: "협상에 의한 계약",
    detailUrl: "https://www.g2b.go.kr/",
    description: "도시철도·버스·마을버스의 환승 체계를 분석하고, 생활권별 노선 개편과 통합요금 정책 대안을 마련하는 연구 용역입니다.",
    tasks: ["교통카드·승하차 데이터 분석", "권역별 노선 재편 시나리오", "통합환승 요금 개편안", "시민·운수업계 의견수렴"],
    qualifications: ["교통·도시 분야 연구용역 수행 실적", "공동수급 가능"],
    attachments: [
      { id: "att-1", name: "제안요청서_대중교통체계개편.pdf", kind: "제안요청서", status: "분석 완료", pages: 54 },
      { id: "att-2", name: "과업지시서.pdf", kind: "과업지시서", status: "분석 완료", pages: 21 },
    ],
    reviewState: "검토 전",
  },
  {
    id: "R26BK00125017-000",
    bidNumber: "R26BK00125017",
    order: "000",
    title: "광역버스 준공영제 운영성과 분석 및 개선방안 연구",
    businessType: "용역",
    status: "정정",
    agency: "경기도",
    demandAgency: "경기도 교통국",
    region: "경기도",
    publishedAt: publishedAt(-1),
    closesAt: closesAt(5),
    budget: 480_000_000,
    budgetLabel: "배정예산 4억 8,000만원",
    contractMethod: "협상에 의한 계약",
    detailUrl: "https://www.g2b.go.kr/",
    description: "광역버스 준공영제 운영자료를 분석하고 배차·노선·재정지원 개선안을 도출합니다.",
    tasks: ["운영성과 진단", "노선·배차 효율화", "재정지원 산식 개선", "정책 로드맵 수립"],
    qualifications: ["교통 정책 연구 실적", "중소기업 제한 경쟁"],
    changeSummary: "제안서 제출 마감이 2일 연장되었습니다.",
    attachments: [
      { id: "att-3", name: "제안요청서_v2.hwp", kind: "제안요청서", status: "부분 분석", pages: 39 },
      { id: "att-4", name: "정정공고문.pdf", kind: "정정공고문", status: "분석 완료", pages: 3 },
    ],
    reviewState: "검토 중",
    memo: "재정지원 모델링 수행 인력 확인 필요",
  },
  {
    id: "R26BK00125029-000",
    bidNumber: "R26BK00125029",
    order: "000",
    title: "스마트 정류장 통합정보 안내시스템 구축",
    businessType: "물품",
    status: "신규",
    agency: "부산광역시",
    demandAgency: "부산광역시 버스운영과",
    region: "부산광역시",
    publishedAt: publishedAt(-1),
    closesAt: closesAt(12),
    budget: 2_100_000_000,
    budgetLabel: "배정예산 21억원",
    contractMethod: "제한경쟁",
    detailUrl: "https://www.g2b.go.kr/",
    description: "정류장 단말기와 실시간 도착정보를 연계하는 통합 안내시스템을 도입합니다.",
    tasks: ["정류장 안내 단말 공급", "교통정보 API 연계", "관제 화면 구축"],
    qualifications: ["직접생산확인증명서", "정보통신공사업 등록"],
    attachments: [
      { id: "att-5", name: "규격서.pdf", kind: "규격서", status: "분석 완료", pages: 42 },
    ],
    reviewState: "검토 전",
  },
  {
    id: "R26BK00125042-000",
    bidNumber: "R26BK00125042",
    order: "000",
    title: "도시철도 역사 청소용역",
    businessType: "용역",
    status: "신규",
    agency: "인천교통공사",
    demandAgency: "인천교통공사",
    region: "인천광역시",
    publishedAt: publishedAt(-1),
    closesAt: closesAt(6),
    budget: 620_000_000,
    budgetLabel: "추정가격 6억 2,000만원",
    contractMethod: "적격심사",
    detailUrl: "https://www.g2b.go.kr/",
    description: "도시철도 역사 및 부대시설의 청소와 환경 관리를 수행합니다.",
    tasks: ["역사 청소", "폐기물 관리", "환경미화 인력 운영"],
    qualifications: ["건물위생관리업"],
    attachments: [
      { id: "att-6", name: "과업내용서.pdf", kind: "과업지시서", status: "분석 완료", pages: 16 },
    ],
    reviewState: "검토 전",
  },
  {
    id: "R26BK00125055-001",
    bidNumber: "R26BK00125055",
    order: "001",
    title: "지역 맞춤형 수요응답형 교통(DRT) 운영모델 설계 연구",
    businessType: "용역",
    status: "재공고",
    agency: "국토교통부",
    demandAgency: "대도시권광역교통위원회",
    region: "전국",
    publishedAt: publishedAt(-1),
    closesAt: closesAt(3),
    budget: 760_000_000,
    budgetLabel: "추정가격 7억 6,000만원",
    contractMethod: "협상에 의한 계약",
    detailUrl: "https://www.g2b.go.kr/",
    description: "인구 감소 지역의 대중교통 공백을 해소하기 위한 DRT 운행권역과 배차 알고리즘, 운영 기준을 설계합니다.",
    tasks: ["교통 취약지역 분석", "DRT 수요예측", "운행권역 설계", "운영·평가 지표 개발"],
    qualifications: ["교통 분야 학술연구용역 실적", "공동수급 가능"],
    attachments: [
      { id: "att-7", name: "제안요청서.pdf", kind: "제안요청서", status: "분석 완료", pages: 47 },
      { id: "att-8", name: "수요자료.xlsx", kind: "참고자료", status: "다운로드 실패" },
    ],
    reviewState: "보관",
  },
  {
    id: "R26BK00124991-000",
    bidNumber: "R26BK00124991",
    order: "000",
    title: "공영주차장 시설물 정비공사",
    businessType: "공사",
    status: "마감",
    agency: "성남시",
    demandAgency: "성남시 도시개발사업단",
    region: "경기도",
    publishedAt: publishedAt(-2),
    closesAt: closesAt(-1),
    budget: 320_000_000,
    budgetLabel: "기초금액 3억 2,000만원",
    contractMethod: "적격심사",
    detailUrl: "https://www.g2b.go.kr/",
    description: "공영주차장 노후 시설을 보수하는 공사입니다.",
    tasks: ["시설물 보수", "도장", "전기 설비 교체"],
    qualifications: ["시설물유지관리업"],
    attachments: [{ id: "att-9", name: "공사시방서.pdf", kind: "시방서", status: "분석 완료", pages: 12 }],
    reviewState: "미참여",
  },
];
