import { RuleAnalysisEngine } from "@/lib/analysis";
import { processAttachment } from "@/lib/attachment-processing";
import { defaultTopic } from "@/lib/topic-default";
import { getBidSource } from "@/lib/sources";
import { createSupabaseAdminClient } from "@/lib/supabase";
import type { BatchRun, BidNotice, Notification, Topic } from "@/lib/types";

type Row = Record<string, unknown>;
const analyzer = new RuleAnalysisEngine();
const array = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
const topicOf = (row: Row): Topic => ({ id: String(row.id), name: String(row.name), description: String(row.description), capabilities: String(row.capabilities ?? ""), includeKeywords: array(row.include_keywords), excludeKeywords: array(row.exclude_keywords), businessTypes: array(row.business_types) as Topic["businessTypes"], regions: array(row.regions), minBudget: row.min_budget === null ? null : Number(row.min_budget), maxBudget: row.max_budget === null ? null : Number(row.max_budget), minimumDays: Number(row.minimum_days), threshold: Number(row.threshold) });
const noticeOf = (row: Row, state?: Row): BidNotice => ({ id: String(row.id), bidNumber: String(row.bid_number), order: String(row.bid_order), title: String(row.title), businessType: String(row.business_type) as BidNotice["businessType"], status: String(row.status) as BidNotice["status"], agency: String(row.agency), demandAgency: String(row.demand_agency), region: String(row.region), publishedAt: String(row.published_at), closesAt: String(row.closes_at), budget: row.budget === null ? null : Number(row.budget), budgetLabel: String(row.budget_label), contractMethod: String(row.contract_method), detailUrl: String(row.detail_url), description: String(row.description), tasks: array(row.tasks), qualifications: array(row.qualifications), changeSummary: String(row.change_summary ?? "") || undefined, attachments: Array.isArray(row.attachments) ? row.attachments.map((item) => { const attachment = item as Row; const text = attachment.attachment_texts as Row | undefined; return { id: String(attachment.id), name: String(attachment.name), kind: String(attachment.kind), status: String(attachment.status) as BidNotice["attachments"][number]["status"], pages: attachment.pages ? Number(attachment.pages) : undefined, sourceUrl: String(attachment.source_url ?? "") || undefined, storagePath: String(attachment.storage_path ?? "") || undefined, failureReason: String(attachment.failure_reason ?? "") || undefined, extractedText: String(text?.extracted_text ?? "") || undefined }; }) : [], analysis: (Array.isArray(row.topic_scores) ? (row.topic_scores[0] as Row | undefined) : row.topic_scores as Row | undefined)?.analysis as BidNotice["analysis"], reviewState: state?.review_state as BidNotice["reviewState"] ?? "검토 전", memo: String(state?.memo ?? "") || undefined });
const runOf = (row: Row): BatchRun => ({ id: String(row.id), startedAt: String(row.started_at), completedAt: row.completed_at ? String(row.completed_at) : undefined, status: String(row.status) as BatchRun["status"], discovered: Number(row.discovered), changed: Number(row.changed), analyzed: Number(row.analyzed), notified: Number(row.notified), apiCalls: Number(row.api_calls) });

export class SupabaseRepository {
  private admin = createSupabaseAdminClient();
  constructor(private userId: string) {}
  async getTopic() { const { data } = await this.admin.from("topics").select("*").order("created_at").limit(1).maybeSingle(); if (data) return topicOf(data); const { data: inserted, error } = await this.admin.from("topics").insert({ user_id: this.userId, name: defaultTopic.name, description: defaultTopic.description, capabilities: defaultTopic.capabilities, include_keywords: defaultTopic.includeKeywords, exclude_keywords: defaultTopic.excludeKeywords, business_types: defaultTopic.businessTypes, regions: defaultTopic.regions, min_budget: defaultTopic.minBudget, max_budget: defaultTopic.maxBudget, minimum_days: defaultTopic.minimumDays, threshold: defaultTopic.threshold }).select().single(); if (error) throw error; return topicOf(inserted); }
  async updateTopic(patch: Partial<Topic>) { const current = await this.getTopic(); const fields: Record<string, unknown> = {}; const map: Record<string, string> = { includeKeywords: "include_keywords", excludeKeywords: "exclude_keywords", businessTypes: "business_types", minBudget: "min_budget", maxBudget: "max_budget", minimumDays: "minimum_days" }; Object.entries(patch).forEach(([key, value]) => { if (key !== "id" && value !== undefined) fields[map[key] ?? key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)] = value; }); const { data, error } = await this.admin.from("topics").update(fields).eq("id", current.id).select().single(); if (error) throw error; return topicOf(data); }
  async listNotices() { const topic = await this.getTopic(); const { data, error } = await this.admin.from("notices").select("*, attachments(*, attachment_texts(*)), topic_scores!left(analysis, topic_id)").order("closes_at"); if (error) throw error; const { data: states } = await this.admin.from("user_bid_states").select("*").eq("user_id", this.userId); const byId = new Map((states ?? []).map((item: Row) => [String(item.notice_id), item])); return (data ?? []).map((row: Row) => noticeOf({ ...row, topic_scores: (row.topic_scores as Row[] | undefined)?.filter((score) => score.topic_id === topic.id) }, byId.get(String(row.id)))); }
  async getNotice(id: string) { return (await this.listNotices()).find((notice) => notice.id === id); }
  async updateNotice(id: string, patch: Pick<BidNotice, "reviewState" | "memo">) { const { error } = await this.admin.from("user_bid_states").upsert({ user_id: this.userId, notice_id: id, review_state: patch.reviewState, memo: patch.memo ?? "", updated_at: new Date().toISOString() }); if (error) throw error; return this.getNotice(id); }
  async listNotifications(): Promise<Notification[]> { const { data, error } = await this.admin.from("notifications").select("*").eq("user_id", this.userId).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map((row: Row) => ({ id: String(row.id), bidId: String(row.notice_id), title: String(row.title), message: String(row.message), createdAt: String(row.created_at), read: Boolean(row.read), score: Number(row.score) })); }
  async markNotificationRead(id: string) { const { data } = await this.admin.from("notifications").update({ read: true }).eq("id", id).eq("user_id", this.userId).select().maybeSingle(); return data ? { id: String(data.id), bidId: String(data.notice_id), title: String(data.title), message: String(data.message), createdAt: String(data.created_at), read: true, score: Number(data.score) } : undefined; }
  async listRuns() { const { data, error } = await this.admin.from("batch_runs").select("*").order("started_at", { ascending: false }).limit(20); if (error) throw error; return (data ?? []).map(runOf); }
  async runDailyAnalysis() { return runBatch(); }
}

export async function runBatch() {
  const admin = createSupabaseAdminClient(); const { data: started, error } = await admin.from("batch_runs").insert({}).select().single(); if (error) throw error;
  try { const notices = await getBidSource().listNotices(new Date(Date.now() - 72 * 3_600_000), new Date()); for (const notice of notices) { const hash = JSON.stringify([notice.title, notice.closesAt, notice.status, notice.description]); const row = { bid_number: notice.bidNumber, bid_order: notice.order, title: notice.title, business_type: notice.businessType, status: notice.status, agency: notice.agency, demand_agency: notice.demandAgency, region: notice.region, published_at: notice.publishedAt, closes_at: notice.closesAt, budget: notice.budget, budget_label: notice.budgetLabel, contract_method: notice.contractMethod, detail_url: notice.detailUrl, description: notice.description, tasks: notice.tasks, qualifications: notice.qualifications, change_summary: notice.changeSummary ?? null, source_hash: hash, updated_at: new Date().toISOString() }; const { data: saved, error: upsertError } = await admin.from("notices").upsert(row, { onConflict: "bid_number,bid_order" }).select().single(); if (upsertError) throw upsertError; await admin.from("notice_versions").upsert({ notice_id: saved.id, source_hash: hash, source_payload: notice }, { onConflict: "notice_id,source_hash" }); for (const attachment of notice.attachments.slice(0, 3)) { const { data: savedAttachment } = await admin.from("attachments").upsert({ notice_id: saved.id, source_url: attachment.sourceUrl ?? `unavailable:${attachment.id}`, name: attachment.name, kind: attachment.kind, status: attachment.status }, { onConflict: "notice_id,source_url" }).select().single(); if (savedAttachment) await admin.from("processing_jobs").upsert({ attachment_id: savedAttachment.id, status: "대기" }, { onConflict: "attachment_id" }); } }
    const { data: queued } = await admin.from("processing_jobs").select("*, attachments(*)").in("status", ["대기", "처리 중"]).lte("run_after", new Date().toISOString()).limit(6);
    for (const job of queued ?? []) { const attachmentRow = job.attachments as Row | undefined; if (!attachmentRow) continue; await admin.from("processing_jobs").update({ status: "처리 중", attempts: Number(job.attempts) + 1 }).eq("id", job.id); const processed = await processAttachment(String(attachmentRow.notice_id), { id: String(attachmentRow.id), name: String(attachmentRow.name), kind: String(attachmentRow.kind), status: String(attachmentRow.status) as BidNotice["attachments"][number]["status"], sourceUrl: String(attachmentRow.source_url) }); await admin.from("attachments").update({ status: processed.status, storage_path: processed.storagePath ?? null, pages: processed.pages ?? null, failure_reason: processed.failureReason ?? null, updated_at: new Date().toISOString() }).eq("id", attachmentRow.id); if (processed.extractedText) await admin.from("attachment_texts").upsert({ attachment_id: attachmentRow.id, extracted_text: processed.extractedText, page_map: [], extractor_version: "mvp-1" }); await admin.from("processing_jobs").update({ status: processed.status === "분석 완료" || processed.status === "부분 분석" || processed.status === "보류" ? "완료" : "실패", failure_reason: processed.failureReason ?? null, updated_at: new Date().toISOString() }).eq("id", job.id); }
    const { data: topics } = await admin.from("topics").select("*"); const { data: rows } = await admin.from("notices").select("*, attachments(*, attachment_texts(*))"); let notified = 0; for (const topicRow of topics ?? []) for (const row of rows ?? []) { const analysis = analyzer.analyze(noticeOf(row), topicOf(topicRow)); await admin.from("topic_scores").upsert({ topic_id: topicRow.id, notice_id: row.id, analysis, score: analysis.score, updated_at: new Date().toISOString() }, { onConflict: "topic_id,notice_id" }); if (analysis.score >= Number(topicRow.threshold) && row.status !== "마감") { const eventKey = `${topicRow.id}:${row.id}:${analysis.score}`; const { error: notificationError } = await admin.from("notifications").upsert({ user_id: topicRow.user_id, notice_id: row.id, title: row.title, message: `${topicRow.name} 주제와 높은 관련성이 확인되었습니다.`, score: analysis.score, event_key: eventKey }, { onConflict: "user_id,event_key", ignoreDuplicates: true }); if (!notificationError) notified += 1; } }
    const { data } = await admin.from("batch_runs").update({ completed_at: new Date().toISOString(), status: "완료", discovered: notices.length, changed: notices.filter((notice) => notice.status === "정정" || notice.status === "재공고").length, analyzed: (topics?.length ?? 0) * (rows?.length ?? 0), notified, api_calls: 4 }).eq("id", started.id).select().single(); return runOf(data);
  } catch (failure) { await admin.from("batch_runs").update({ completed_at: new Date().toISOString(), status: "부분 완료", error_summary: failure instanceof Error ? failure.message : "알 수 없는 오류" }).eq("id", started.id); throw failure; }
}
