"use client";
import { FormEvent, useEffect, useState } from "react";

type Topic = { name: string; description: string; capabilities: string; includeKeywords: string[]; excludeKeywords: string[]; minimumDays: number; threshold: number };
const emptyTopic: Topic = { name: "", description: "", capabilities: "", includeKeywords: [], excludeKeywords: [], minimumDays: 3, threshold: 70 };

export default function AdminPage() {
  const [code, setCode] = useState(""); const [authorized, setAuthorized] = useState(false); const [message, setMessage] = useState(""); const [topic, setTopic] = useState(emptyTopic); const [hasNaraKey, setHasNaraKey] = useState(false);
  async function login(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); if (!response.ok) { setMessage((await response.json()).message); return; } setAuthorized(true); setMessage(""); }
  useEffect(() => { if (!authorized) return; fetch("/api/admin/settings").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "관리자 설정을 불러오지 못했습니다."); return data; }).then((data) => { if (data.topic) setTopic({ ...emptyTopic, ...data.topic, includeKeywords: data.topic.include_keywords ?? data.topic.includeKeywords ?? [], excludeKeywords: data.topic.exclude_keywords ?? data.topic.excludeKeywords ?? [] }); setHasNaraKey(Boolean(data.hasNarajangteoKey)); }).catch((error) => setMessage(error instanceof Error ? error.message : "관리자 설정을 불러오지 못했습니다.")); }, [authorized]);
  async function save(event: FormEvent) { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic: { name: form.get("name"), description: form.get("description"), capabilities: form.get("capabilities"), includeKeywords: String(form.get("includeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), excludeKeywords: String(form.get("excludeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), minimumDays: Number(form.get("minimumDays")), threshold: Number(form.get("threshold")) } }) }); setMessage(response.ok ? "탐색 설정을 저장했습니다." : (await response.json()).message); }
  if (!authorized) return <main className="login-shell"><section className="login-card"><p className="eyebrow">BIDFIT · ADMIN</p><h1>관리자 페이지</h1><p>관리자 코드를 입력하면 설정 화면에 접근할 수 있습니다.</p><form onSubmit={login}><label htmlFor="admin-code">관리자 코드</label><input id="admin-code" type="password" value={code} onChange={(e) => setCode(e.target.value)} required /><button>관리자 페이지 열기</button></form>{message && <p role="alert">{message}</p>}</section></main>;
  return <main className="login-shell"><section className="login-card admin-settings"><p className="eyebrow">BIDFIT · ADMIN SETTINGS</p><h1>수집·탐색 설정</h1><p>탐색 주제와 분석 기준을 수정합니다. 비밀키는 이 화면에 입력하거나 저장하지 않습니다.</p><div className={hasNaraKey ? "config-status ready" : "config-status warning"}><strong>{hasNaraKey ? "나라장터 API 연결 설정됨" : "나라장터 API Key 미설정"}</strong><span>{hasNaraKey ? "Vercel 서버 환경변수에서 읽습니다." : "Vercel Production 환경변수 NARAJANGTEO_SERVICE_KEY에 등록해야 합니다."}</span></div><form onSubmit={save}><label>탐색 주제<input name="name" defaultValue={topic.name} required /></label><label>주제 설명<textarea name="description" defaultValue={topic.description} rows={3} required /></label><label>보유 역량<textarea name="capabilities" defaultValue={topic.capabilities} rows={2} /></label><label>포함 키워드<input name="includeKeywords" defaultValue={topic.includeKeywords.join(", ")} /></label><label>제외 키워드<input name="excludeKeywords" defaultValue={topic.excludeKeywords.join(", ")} /></label><label>최소 잔여일<input name="minimumDays" type="number" min="0" defaultValue={topic.minimumDays} /></label><label>알림 기준 점수<input name="threshold" type="number" min="0" max="100" defaultValue={topic.threshold} /></label><button>탐색 설정 저장</button></form>{message && <p role="status">{message}</p>}<a href="/">공개 공고 화면으로 돌아가기</a></section></main>;
}
