"use client";
import { FormEvent, useEffect, useState } from "react";

type Topic = { name: string; description: string; capabilities: string; includeKeywords: string[]; excludeKeywords: string[]; minimumDays: number; threshold: number };
const emptyTopic: Topic = { name: "", description: "", capabilities: "", includeKeywords: [], excludeKeywords: [], minimumDays: 3, threshold: 70 };

export default function AdminPage() {
  const [code, setCode] = useState(""); const [authorized, setAuthorized] = useState(false); const [message, setMessage] = useState(""); const [topic, setTopic] = useState(emptyTopic); const [key, setKey] = useState(""); const [hasKey, setHasKey] = useState(false);
  async function login(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); if (!response.ok) { setMessage((await response.json()).message); return; } setAuthorized(true); setMessage(""); }
  useEffect(() => { if (!authorized) return; fetch("/api/admin/settings").then((response) => response.json()).then((data) => { if (data.topic) setTopic({ ...emptyTopic, ...data.topic, includeKeywords: data.topic.include_keywords ?? data.topic.includeKeywords ?? [], excludeKeywords: data.topic.exclude_keywords ?? data.topic.excludeKeywords ?? [] }); setHasKey(data.hasNarajangteoKey); }); }, [authorized]);
  async function save(event: FormEvent) { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ narajangteoServiceKey: key, topic: { name: form.get("name"), description: form.get("description"), capabilities: form.get("capabilities"), includeKeywords: String(form.get("includeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), excludeKeywords: String(form.get("excludeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), minimumDays: Number(form.get("minimumDays")), threshold: Number(form.get("threshold")) } }) }); setMessage(response.ok ? "관리자 설정을 저장했습니다." : (await response.json()).message); if (response.ok) { setHasKey(Boolean(key) || hasKey); setKey(""); } }
  if (!authorized) return <main className="login-shell"><section className="login-card"><p className="eyebrow">BIDFIT · ADMIN</p><h1>관리자 페이지</h1><p>관리자 코드를 입력하면 설정 화면에 접근할 수 있습니다.</p><form onSubmit={login}><label htmlFor="admin-code">관리자 코드</label><input id="admin-code" type="password" value={code} onChange={(e) => setCode(e.target.value)} required /><button>관리자 페이지 열기</button></form>{message && <p role="alert">{message}</p>}</section></main>;
  return <main className="login-shell"><section className="login-card admin-settings"><p className="eyebrow">BIDFIT · ADMIN SETTINGS</p><h1>수집·탐색 설정</h1><p>키는 서버에만 저장되며 화면에 다시 표시하지 않습니다.</p><form onSubmit={save}><label>나라장터 API Key<input type="password" value={key} onChange={(e) => setKey(e.target.value)} placeholder={hasKey ? "기존 키가 저장되어 있습니다. 변경 시 입력" : "서비스 키 입력"} /></label><label>탐색 주제<input name="name" defaultValue={topic.name} required /></label><label>주제 설명<textarea name="description" defaultValue={topic.description} rows={3} required /></label><label>보유 역량<textarea name="capabilities" defaultValue={topic.capabilities} rows={2} /></label><label>포함 키워드<input name="includeKeywords" defaultValue={topic.includeKeywords.join(", ")} /></label><label>제외 키워드<input name="excludeKeywords" defaultValue={topic.excludeKeywords.join(", ")} /></label><label>최소 잔여일<input name="minimumDays" type="number" min="0" defaultValue={topic.minimumDays} /></label><label>알림 기준 점수<input name="threshold" type="number" min="0" max="100" defaultValue={topic.threshold} /></label><button>설정 저장</button></form>{message && <p role="status">{message}</p>}<a href="/">공개 공고 화면으로 돌아가기</a></section></main>;
}
