"use client";
import { FormEvent, useEffect, useState } from "react";

type Check = { key: string; label: string; status: "ready" | "missing" | "error"; detail: string; action: string };
type Topic = { name: string; description: string; capabilities: string; includeKeywords: string[]; excludeKeywords: string[]; minimumDays: number; threshold: number };
const emptyTopic: Topic = { name: "", description: "", capabilities: "", includeKeywords: [], excludeKeywords: [], minimumDays: 3, threshold: 70 };

export default function AdminPage() {
  const [code, setCode] = useState(""); const [authorized, setAuthorized] = useState(false); const [message, setMessage] = useState(""); const [checks, setChecks] = useState<Check[]>([]); const [topic, setTopic] = useState(emptyTopic); const [running, setRunning] = useState(false);
  async function login(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); if (!response.ok) { setMessage((await response.json()).message); return; } setAuthorized(true); setMessage(""); }
  useEffect(() => { fetch("/api/admin/session", { cache: "no-store" }).then((response) => response.json()).then((data) => setAuthorized(Boolean(data.authenticated))).catch(() => undefined); }, []);
  useEffect(() => { if (!authorized) return; fetch("/api/admin/setup").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setChecks(data.checks ?? []); if (data.ready) return fetch("/api/admin/settings").then((settings) => settings.json()); return null; }).then((data) => { if (data?.topic) setTopic({ ...emptyTopic, ...data.topic, includeKeywords: data.topic.include_keywords ?? data.topic.includeKeywords ?? [], excludeKeywords: data.topic.exclude_keywords ?? data.topic.excludeKeywords ?? [] }); }).catch((error) => setMessage(error instanceof Error ? error.message : "설정 진단에 실패했습니다.")); }, [authorized]);
  async function save(event: FormEvent) { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic: { name: form.get("name"), description: form.get("description"), capabilities: form.get("capabilities"), includeKeywords: String(form.get("includeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), excludeKeywords: String(form.get("excludeKeywords")).split(",").map((v) => v.trim()).filter(Boolean), minimumDays: Number(form.get("minimumDays")), threshold: Number(form.get("threshold")) } }) }); setMessage(response.ok ? "탐색 설정을 저장했습니다." : (await response.json()).message); }
  async function logout() { await fetch("/api/admin/session", { method: "DELETE" }); setAuthorized(false); setCode(""); }
  async function runRecovery() { setRunning(true); setMessage("오늘의 수집·첨부문서 분석을 시작했습니다. 완료까지 최대 5분이 걸릴 수 있습니다."); try { const response = await fetch("/api/runs", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "분석 실행에 실패했습니다."); setMessage(`오늘의 분석이 완료되었습니다. 수집 ${result.discovered ?? 0}건 · 문서 처리 ${result.attachmentProcessed ?? 0}건 · 분석 ${result.analyzed ?? 0}건`); } catch (error) { setMessage(error instanceof Error ? error.message : "분석 실행에 실패했습니다."); } finally { setRunning(false); } }
  if (!authorized) return <main className="login-shell"><section className="login-card"><p className="eyebrow">BIDFIT · ADMIN</p><h1>관리자 페이지</h1><p>관리자 코드를 입력하면 설정 진단과 운영 화면에 접근할 수 있습니다.</p><form onSubmit={login}><label htmlFor="admin-code">관리자 코드</label><input id="admin-code" type="password" value={code} onChange={(e) => setCode(e.target.value)} required /><button>관리자 페이지 열기</button></form>{message && <p role="alert">{message}</p>}</section></main>;
  const ready = checks.length > 0 && checks.every((check) => check.status === "ready");
  return <main className="login-shell"><section className="login-card admin-settings"><div className="admin-heading"><div><p className="eyebrow">BIDFIT · ADMIN SETTINGS</p><h1>{ready ? "수집·탐색 설정" : "초기 설정 진단"}</h1></div><button type="button" className="secondary-button" onClick={logout}>로그아웃</button></div>{ready ? <><p>탐색 주제와 분석 기준을 수정합니다. 비밀키는 이 화면에 입력하거나 저장하지 않습니다.</p><form onSubmit={save}><label>탐색 주제<input name="name" defaultValue={topic.name} required /></label><label>주제 설명<textarea name="description" defaultValue={topic.description} rows={3} required /></label><label>보유 역량<textarea name="capabilities" defaultValue={topic.capabilities} rows={2} /></label><label>포함 키워드<input name="includeKeywords" defaultValue={topic.includeKeywords.join(", ")} /></label><label>제외 키워드<input name="excludeKeywords" defaultValue={topic.excludeKeywords.join(", ")} /></label><label>최소 잔여일<input name="minimumDays" type="number" min="0" defaultValue={topic.minimumDays} /></label><label>추천 기준 점수<input name="threshold" type="number" min="0" max="100" defaultValue={topic.threshold} /></label><button>탐색 설정 저장</button></form><section className="recovery-run"><strong>관리자용 복구 실행</strong><p>배포 또는 설정 변경으로 정기 실행을 놓친 경우에만 사용합니다. 일반적인 일일 갱신은 매일 08:00~09:00 KST에 자동으로 실행됩니다.</p><button type="button" className="secondary-button" disabled={running} onClick={runRecovery}>{running ? "수집·분석 실행 중…" : "오늘 분석 재실행"}</button></section></> : <SetupChecklist checks={checks} />}{message && <p role="status">{message}</p>}<a href="/">공개 공고 화면으로 돌아가기</a></section></main>;
}

function SetupChecklist({ checks }: { checks: Check[] }) { return <div className="setup-checklist">{checks.map((check) => <article key={check.key} className={`setup-check ${check.status}`}><div><strong>{check.status === "ready" ? "✓" : "!"} {check.label}</strong><span>{check.detail}</span></div>{check.status !== "ready" && <small>{check.action}</small>}</article>)}</div>; }
